//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindAzure2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactContactDevice
    {
        public int Identifier { get; set; }
        public Nullable<int> ContactIdentifier { get; set; }
        public Nullable<int> PhoneTypeIdenitfier { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
