//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindAzure2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageData
    {
        public int ImageID { get; set; }
        public byte[] ImageData1 { get; set; }
        public string Description { get; set; }
    }
}
